# Generated by Django 5.1.1 on 2024-09-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Equipment", "0002_organization_plant_equipment_plant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clientName", models.CharField(max_length=255)),
            ],
        ),
    ]
