# Generated by Django 5.1.1 on 2024-09-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Equipment", "0003_client"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
    ]
