# Generated by Django 5.1.1 on 2024-09-26 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Equipment", "0006_driventype_drivertype_equipment_driven_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="equipment",
            name="unique_equipment_tag_plant",
        ),
        migrations.AlterField(
            model_name="plant",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plants",
                to="Equipment.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipment",
            constraint=models.UniqueConstraint(
                fields=("tag", "plant", "driver_type", "driven_type"),
                name="unique_equipment_tag_plant",
            ),
        ),
    ]
