# Generated by Django 5.1.1 on 2024-09-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Equipment", "0007_remove_equipment_unique_equipment_tag_plant_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="equipment",
            name="unique_equipment_tag_plant",
        ),
        migrations.AddConstraint(
            model_name="equipment",
            constraint=models.UniqueConstraint(
                fields=("tag", "plant"), name="unique_equipment_tag_plant"
            ),
        ),
    ]
