# Generated by Django 5.1.1 on 2024-09-26 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Equipment", "0008_remove_equipment_unique_equipment_tag_plant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="driven_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Equipment.driventype",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="driver_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Equipment.drivertype",
            ),
        ),
    ]
